---
title: "NY NOAA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(p8105.datasets)
```

```{r}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  # create separate variables for year, month, and day.
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  # make the observations for temperature and precipitation in reasonable units
  mutate(tmax = as.numeric(tmax),
         tmin = as.numeric(tmin)) %>% 
  mutate(prcp = prcp/10,
         tmax = tmax/10,
         tmin = tmin/10) %>% 
  # filter to be no NAs
  filter(!is.na(tmax),
         !is.na(tmin)) %>% 
  # limit the sample size to be 5000
  sample_n(5000) 
```


Column {data-width=500}
-----------------------------------------------------------------------

### The average maximum temperature from year 2005 to 2010 in each month

```{r}
ny_noaa %>%
  # filter the dataset for only January and July
  filter(year %in% 2005:2010) %>% 
  group_by(year, month) %>% 
  summarize(average_tmax = mean(tmax, na.rm = TRUE)) %>% 
  plot_ly(x = ~month, y = ~average_tmax, color = ~year, type = "bar")
```

Column {data-width=500}
-----------------------------------------------------------------------

### The distribution of snowfall values greater than 0 and less than 100 separately by year

```{r}
ny_noaa %>% 
  # filter the snowfall value from greater than 0 and less than 100
  filter(snow %in% 1:99) %>% 
  plot_ly(y = ~snow, color = ~year, type = "box")
```

### The maximum and minimum temperature in each year

```{r}
ny_noaa %>% 
  sample_n(500) %>% 
  plot_ly(x = ~tmax, y = ~tmin, color = ~year, type = "scatter", mode = "markers")
```

